function [ configs ] = configs()
%CONFIGS 此处显示有关此函数的摘要
%   此处显示详细说明
configs = struct( ...
'display_info', struct( ...
	'seat_distance', 40, ...
     ...
	'background_color', [127, 127, 127], ...
    'prepare_color', [150, 150, 150], ...
	'fixation_color', [0, 0, 0], ...
	'fixation_radius', 0.2, ...
	'fixation_duration', 1, ...
	'intertrial_duration', 1.5, ...
     ...
	'sure_reward_rect', [-3, -3, 3, 3], ...
	'sure_reward_size', 1, ... % fontsize
	'sure_reward_duration', 1.25, ...
	'sure_reward_locus', [0.5, 0.5], ...
     ...
	'gamble_rect', [-3, -3, 0, 3, -0, -3, 3, 3], ...
	'gamble_size', 2, ...
	'gamble_durations', [1.5], ...
    'interstimulus_interval', 0.25, ...
	'gamble_locus', [0.5, 0.5], ...
     ...
	'fig_color', [0, 0, 0], ...
    'payoff_color', [250 0 0; 0 250 0], ...
	'rect_pen_width', 0.2, ...
	'rect_color', [150, 150, 150], ...
	 ...
	'ready_to_choose_color', [150, 150, 150], ...
	'fail_to_choose_color', [150, 150, 150], ...
	 ...
	'exit_key', 'Escape', ...
	'sure_reward_key', 'UpArrow', ...
	'gamble_key', 'DownArrow', ...
	'time_limit', 2 ...
), ...
'design_info', struct( ...
	'max_payoff', 9, ...
	'payoff_unit', 1, ...
	'sure_rewards_per_gamble', 4, ...
	'gambles_per_trial', [1], ...
	'gambles_per_norm_trial', [7], ...
	'norm_trial_pr', 0.8, ...
	'max_n_gambles', 10, ...
	'blocks_per_duration', 2, ...
    'n_practice_1', 1, ...
    'n_practice_2', 2, ...
    'sure_reward_sigma', 5.45 ...
) ...
);
end

